CREATE TABLE IF NOT EXISTS conversation_turns (
  id INTEGER PRIMARY KEY,
  session_id VARCHAR(100) NOT NULL,
  role VARCHAR(20) NOT NULL,
  content TEXT NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
